# Generated by Django 4.0.5 on 2022-06-21 10:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vicinage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('details', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hood',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hood',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='business',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='business',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='county',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='health_department',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='police_department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_id',
        ),
        migrations.AddField(
            model_name='business',
            name='bs_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bs_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='business',
            name='bs_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='https://web.facebook.com/', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='https://www.instagram.com/', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='https://twitter.com/', max_length=100),
        ),
        migrations.AddField(
            model_name='hood',
            name='emergency_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='hoodimage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='hoodimage'),
        ),
        migrations.AddField(
            model_name='hood',
            name='police_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='vicinage.hood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='vicinage.hood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='vicinage.profile'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='vicinage.profile'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='news',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_post', to='vicinage.hood'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='vicinage.profile'),
        ),
    ]
